/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        cream: '#FFFDF8',
        paper: '#FFFAF2',
        lavbg: '#F8F9FF',
        ink: '#211D2E',
        muted: '#6B6580',
        faint: '#B9B3CC',
        coral: '#FF6B4A',
        coralDeep: '#F04E23',
        grape: '#7C5CFF',
        electric: '#2E9BFF',
        lime: '#58CC02',
        sunny: '#FFB020',
        candy: '#FF7BAC',
        mint: '#00C48C',
        surface: '#FFFFFF',
        neon: '#FF6B4A',
        royal: '#7C5CFF',
        danger: '#FF4B5C',
        warn: '#FFB020',
        gold: '#FFB020',
        sky: '#2E9BFF',
        void: '#FFFDF8',
        abyss: '#FFFAF2',
        panel: '#FFFFFF',
        volt: '#58CC02',
        aqua: '#2E9BFF',
        line: 'rgba(120,100,180,0.10)',
      },
      fontFamily: {
        display: ['Fredoka', '"Plus Jakarta Sans"', 'Inter', 'system-ui', 'sans-serif'],
        body: ['"Plus Jakarta Sans"', 'Inter', 'system-ui', 'sans-serif'],
        funky: ['Fredoka', '"Plus Jakarta Sans"', 'sans-serif'],
        num: ['"Plus Jakarta Sans"', 'Inter', 'system-ui', 'sans-serif'],
        mono: ['"IBM Plex Mono"', 'ui-monospace', 'monospace'],
      },
      boxShadow: {
        soft: '0 20px 50px rgba(80,60,120,0.08)',
        lift: '0 24px 60px -18px rgba(255,107,74,0.28), 0 18px 44px -20px rgba(124,92,255,0.30)',
        card: '0 20px 50px rgba(80,60,120,0.08)',
        sticker: '0 8px 24px rgba(80,60,120,0.12)',
        'sticker-sm': '0 4px 14px rgba(80,60,120,0.10)',
        neon: '0 12px 32px -8px rgba(255,107,74,0.45)',
      },
      keyframes: {
        floaty: { '0%, 100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-10px)' } },
        orbA: { '0%,100%': { transform: 'translate(0,0) scale(1)' }, '50%': { transform: 'translate(60px,30px) scale(1.12)' } },
        orbB: { '0%,100%': { transform: 'translate(0,0) scale(1)' }, '50%': { transform: 'translate(-50px,40px) scale(1.08)' } },
        orbit: { from: { transform: 'rotate(0deg)' }, to: { transform: 'rotate(360deg)' } },
        'orbit-rev': { from: { transform: 'rotate(360deg)' }, to: { transform: 'rotate(0deg)' } },
        sparkle: { '0%,100%': { opacity: '0.2', transform: 'scale(0.8)' }, '50%': { opacity: '0.9', transform: 'scale(1.2)' } },
        pulseGlow: { '0%,100%': { opacity: '0.5' }, '50%': { opacity: '1' } },
      },
      animation: {
        floaty: 'floaty 7s ease-in-out infinite',
        orbA: 'orbA 14s ease-in-out infinite',
        orbB: 'orbB 18s ease-in-out infinite',
        orbit: 'orbit 26s linear infinite',
        'orbit-rev': 'orbit-rev 32s linear infinite',
        sparkle: 'sparkle 3s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};
